version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gatepass_db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - gatepass_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gatepass_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gatepass.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  gatepass_postgres_data: